import type { NextPage } from "next";
import Head from "next/head";
import { Buttons } from "../components/buttons/buttons.component";
import { AuthService } from "../lib/auth-service/auth.service";

const Home: NextPage = () => {
   const authLogin = new AuthService();

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         {/* these are all of the auth functions in action */}
         <button onClick={authLogin.googleSignIn}>google</button>
         <button onClick={authLogin.facebookSignIn}>facebook</button>

         <button
            onClick={() => {
               authLogin.signup({
                  email: "ozzy123@123.com",
                  password: "Ozzzy123Ee",
               });
            }}
         >
            create
         </button>

         <button
            onClick={() => {
               authLogin.signinPassword({
                  email: "ozzy123@123.com",
                  password: "Ozzzy123Ee",
               });
            }}
         >
            log in
         </button>
         <button onClick={authLogin.signOut}>log out</button>
         <Buttons dark={true}>login</Buttons>
      </>
   );
};

export default Home;
